### ISSUE TITLE
is it possible to add partition?

### ISSUE THREAD

**Issue by royanon** [lucabecchetti/laravel-mysql-partition#1]
Because re-do the whole table partitions takes a long time, can we have a way to add a new partition that will re-organize the future partition?

**Comment by lucabecchetti** [comment]
I'm sorry, Not for now!

**Comment by ipearx** [comment]
For anyone else reading this, one answer is to re-structure and split the 'future' partition, to create the new partition you want. The technique is described here 
http://mysql.rjweb.org/doc.php/partitionmaint

This library doesn't support it, so I issued a mysql statement directly e.g.
```
DB::statement("ALTER TABLE tracking REORGANIZE PARTITION future INTO (
				PARTITION p" . $tomorrow . " VALUES LESS THAN (".$tomorrow."), 
				PARTITION future VALUES LESS THAN MAXVALUE
			);");
```
Keep in mind:
- If using partition by range and using LESS THAN, the new partition must be greater than the previous greatest partition.
- For me $tomorrow is a unix timestamp for the end of the day of tomorrow.
