### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by deviddev** [lucabecchetti/laravel-mysql-partition#13]
Are you planning the Laravel 10 support?

**Comment by lucabecchetti** [comment]
Yes but i don't know when.. probably during this month! i'm not sure!

**Comment by deviddev** [comment]
Thank you, we are witing for it.

**Comment by scramatte** [comment]
+1  here

**Comment by joe820912boy** [comment]
+1, seems that now is not working with laravel 10

**Comment by Ijazweb** [comment]
+1 here

**Comment by lucabecchetti** [comment]
version 1.2.0 is out
