### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by datnguyen293** [lucabecchetti/laravel-mysql-partition#4]
This is very helpful package I have used much for my apps. Currently I have to upgrade the app to Laravel 8 (for Job Batching) but this package is not compatible with Laravel 8 yet.
Can you please publish a supported version to Packagist?

Thanks

**Comment by lucabecchetti** [comment]
Hi, thanks for using my package! I'm fully of work now, I will fix as soon as will be possible!

**Comment by lucabecchetti** [comment]
Update to new versione 1.0.12
