### ISSUE TITLE
Dynamic partition range

### ISSUE THREAD

**Issue by digitall-it** [lucabecchetti/laravel-mysql-partition#9]
Is it possible to have a structure where the partition zoning is dynamic, for example
Current: current year
Archive: less than current year

or

Current: last 12 months
Archive: more than 12 months

and migrate all the data from one partition to another in a scheduled Laravel task or automatically by the database?

This would make a very useful and automatic use case for the package. 

By the way, greetings from Ischia, Napoli.

**Comment by lucabecchetti** [comment]
I'm sorry... there is no this feature at the moment!

**Comment by ipearx** [comment]
> Is it possible to have a structure where the partition zoning is dynamic, for example Current: current year Archive: less than current year

Why do this? The main advantage of a partition is to delete bulk old data fast. If you're keeping old data, you might as well use a single big table, with an index by date? This article was handy to explain it to me:
http://mysql.rjweb.org/doc.php/partitionmaint

**Comment by digitall-it** [comment]
Thank you, the article is illuminating on some myths on partitioning.
